version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: proteus_api
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - MONGO_URI=mongodb://root:password@mongodb:27017/proteus_db?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb-proteus
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
